### ISSUE TITLE
Running Example wiki needs update

### ISSUE THREAD

**Issue by atroutt** [Comcast/jrugged#63]
https://github.com/Comcast/jrugged/wiki/Running-Example-App

Has old instructions in it. It says 
"TODO Alert*: These steps need to be updated somewhat, as the examples are now a sub-project of the mainline codebase. However, the steps are similar in spirit to what's below."

i'd like to update those

**Comment by atroutt** [comment]
I am going to change the instructions to ```Steps to get an example app up and running quickly.

To run the example app:

* Fork and clone project
* cd jrugged
* mvn install (from the root of this project)
* cd jrugged-examples
* mvn jetty:run
* Point your browser to http://localhost:8080/jrugged-examples and start clicking links.```

**Comment by atroutt** [comment]
The wiki has been updated!

**Comment by joercampbell** [comment]
Merged/Changed!
